### ISSUE TITLE
Pre-release checklist

### ISSUE THREAD

**Issue by aahnik** [web3ssh-iiits/web3ssh-24#15]
we need to check everything properly before making this site public

- [ ] each and every link should work correctly
- [ ] check on different mobile devices (at least 10)
- [ ] check on browser by emulating all screen sizes
- [ ] check on all major browsers: edge, safari, brave, chrome, firefox + others
- [ ] optimize image/graphics loading
- [ ] check how animations are working on different devices
- [ ] check how scroll components are working on different devices
